//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake.Npm.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cake.Npm.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;module-name&quot;,
        ///  &quot;version&quot;: &quot;10.3.1&quot;,
        ///  &quot;description&quot;: &quot;An example module to illustrate the usage of a package.json&quot;,
        ///  &quot;author&quot;: &quot;Your Name &lt;you.name@example.org&gt;&quot;,
        ///  &quot;contributors&quot;: [{
        ///  &quot;name&quot;: &quot;Foo Bar&quot;,
        ///  &quot;email&quot;: &quot;foo.bar@example.com&quot;
        ///}],
        ///  &quot;bin&quot;: {
        ///  &quot;module-name&quot;: &quot;./bin/module-name&quot;
        ///},
        ///  &quot;scripts&quot;: {
        ///    &quot;test&quot;: &quot;vows --spec --isolate&quot;,
        ///    &quot;start&quot;: &quot;node index.js&quot;,
        ///    
        ///    
        ///    &quot;prepublish&quot;: &quot;coffee --bare --compile --output lib/foo src/foo/*.coffee&quot;
        ///  },
        ///  &quot;main&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SamplePackageJson {
            get {
                return ResourceManager.GetString("SamplePackageJson", resourceCulture);
            }
        }
    }
}
